FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q && apt-get install -qy \
    texlive-full \
    python-pygments gnuplot python3-pip \
    make git \
    && rm -rf /var/lib/apt/lists/*
RUN pip install Pygments
WORKDIR /data
VOLUME ["/data"]
